version: '3'

services:
  app:
    image: app
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - r
    
  json_server:
    image: json_server
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - r


networks:
  r: