[package]
name = "auth_server"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0"
app_interface = { path = "../../interface" }
sqlx = {version = "0.7.4", features = ["mysql"]}

[dependencies.rocket_db_pools]
version = "0.1.0"
features = ["sqlx_mysql"]